/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/work/index" |
       "/pages/task/index" |
       "/pages/colab/index" |
       "/pages/contacts/index" |
       "/pages/login/forget" |
       "/pages/login/index" |
       "/pages/login/phoneIndex" |
       "/pages/login/registerCode" |
       "/pages/message/index" |
       "/pages/my/index" |
       "/pages/my-info/index" |
       "/pages/person-center/index" |
       "/pages/role/edit" |
       "/pages/role/index" |
       "/pages/role/show" |
       "/pages/user/edit" |
       "/pages/user/index" |
       "/pages/user/show" |
       "/pages/colab/detail/index" |
       "/pages/my/contact-service/index" |
       "/pages/my/helper/index" |
       "/pages/my/mail/index" |
       "/pages/my/system-setting/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/message/index" | "/pages/colab/index" | "/pages/work/index" | "/pages/contacts/index" | "/pages/my/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
